export const weatherCodeMapping = {
  0: {
    weatherCondition: "Clear sky",
    imgDay: "DAY_00",
    imgNightFullMoon: "NFM_00",
    imgNightHalfMoon: "NHM_00",
  },
  1: {
    weatherCondition: "Mainly clear",
    imgDay: "DAY_01",
    imgNightFullMoon: "NFM_01",
    imgNightHalfMoon: "NHM_01",
  },
  2: {
    weatherCondition: "Partly cloudy",
    imgDay: "DAY_02",
    imgNightFullMoon: "NFM_02",
    imgNightHalfMoon: "NHM_02",
  },
  3: {
    weatherCondition: "Overcast",
    imgDay: "DAY_03",
    imgNightFullMoon: "NFM_03",
    imgNightHalfMoon: "NHM_03",
  },
  45: {
    weatherCondition: "Fog",
    imgDay: "DAY_45",
    imgNightFullMoon: "NFM_45",
    imgNightHalfMoon: "NHM_45",
  },
  48: {
    weatherCondition: "Rime fog",
    imgDay: "DAY_48",
    imgNightFullMoon: "NFM_48",
    imgNightHalfMoon: "NHM_48",
  },
  51: {
    weatherCondition: "Drizzle (light)",
    imgDay: "DAY_51",
    imgNightFullMoon: "NFM_51",
    imgNightHalfMoon: "NHM_51",
  },
  53: {
    weatherCondition: "Drizzle (moderate)",
    imgDay: "DAY_53",
    imgNightFullMoon: "NFM_53",
    imgNightHalfMoon: "NHM_53",
  },
  55: {
    weatherCondition: "Drizzle (dense)",
    imgDay: "DAY_55",
    imgNightFullMoon: "NFM_55",
    imgNightHalfMoon: "NHM_55",
  },
  56: {
    weatherCondition: "Freezing drizzle (light)",
    imgDay: "DAY_56",
    imgNightFullMoon: "NFM_56",
    imgNightHalfMoon: "NHM_56",
  },
  57: {
    weatherCondition: "Freezing drizzle (dense)",
    imgDay: "DAY_57",
    imgNightFullMoon: "NFM_57",
    imgNightHalfMoon: "NHM_57",
  },
  61: {
    weatherCondition: "Rain (slight)",
    imgDay: "DAY_61",
    imgNightFullMoon: "NFM_61",
    imgNightHalfMoon: "NHM_61",
  },
  63: {
    weatherCondition: "Rain (moderate)",
    imgDay: "DAY_63",
    imgNightFullMoon: "NFM_63",
    imgNightHalfMoon: "NHM_63",
  },
  65: {
    weatherCondition: "Rain (heavy)",
    imgDay: "DAY_65",
    imgNightFullMoon: "NFM_65",
    imgNightHalfMoon: "NHM_65",
  },
  66: {
    weatherCondition: "Freezing rain (light)",
    imgDay: "DAY_66",
    imgNightFullMoon: "NFM_66",
    imgNightHalfMoon: "NHM_66",
  },
  67: {
    weatherCondition: "Freezing rain (heavy)",
    imgDay: "DAY_67",
    imgNightFullMoon: "NFM_67",
    imgNightHalfMoon: "NHM_67",
  },
  71: {
    weatherCondition: "Snow (slight)",
    imgDay: "DAY_71",
    imgNightFullMoon: "NFM_71",
    imgNightHalfMoon: "NHM_71",
  },
};